CREATE TABLE
    IF NOT EXISTS computer (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        -- Core components
        pc_case_id INTEGER,
        motherboard_id INTEGER,
        cpu_id INTEGER,
        cpu_cooler_id INTEGER,
        thermal_paste_id INTEGER,
        memory_id INTEGER,
        video_card_id INTEGER,
        sound_card_id INTEGER,
        external_hard_drive_id INTEGER,
        internal_hard_drive_id INTEGER,
        power_supply_id INTEGER,
        os_id INTEGER,
        -- Peripherals
        monitor_id INTEGER,
        webcam_id INTEGER,
        keyboard_id INTEGER,
        speakers_id INTEGER,
        headphones_id INTEGER,
        mouse_id INTEGER,
        FOREIGN KEY (keyboard_id) REFERENCES keyboard (id),
        FOREIGN KEY (speakers_id) REFERENCES speakers (id),
        FOREIGN KEY (memory_id) REFERENCES memory (id),
        FOREIGN KEY (thermal_paste_id) REFERENCES thermal_paste (id),
        FOREIGN KEY (pc_case_id) REFERENCES pc_case (id),
        FOREIGN KEY (monitor_id) REFERENCES monitor (id),
        FOREIGN KEY (cpu_cooler_id) REFERENCES cpu_cooler (id),
        FOREIGN KEY (motherboard_id) REFERENCES motherboard (id),
        FOREIGN KEY (video_card_id) REFERENCES video_card (id),
        FOREIGN KEY (cpu_id) REFERENCES cpu (id),
        FOREIGN KEY (mouse_id) REFERENCES mouse (id),
        FOREIGN KEY (webcam_id) REFERENCES webcam (id),
        FOREIGN KEY (external_hard_drive_id) REFERENCES external_hard_drive (id),
        FOREIGN KEY (os_id) REFERENCES os (id),
        FOREIGN KEY (headphones_id) REFERENCES headphones (id),
        FOREIGN KEY (power_supply_id) REFERENCES power_supply (id),
        FOREIGN KEY (internal_hard_drive_id) REFERENCES internal_hard_drive (id),
        FOREIGN KEY (sound_card_id) REFERENCES sound_card (id)
    )